### ISSUE TITLE
https://twitter.com/gchrupala/status/941284551627870208

### ISSUE THREAD

**Issue by samuelbroscheit** [gchrupala/vgs#1]
I have no Twitter account, but I am replying to 

https://twitter.com/gchrupala/status/941284551627870208

In rhn.py in lines 83-85:
 
        for l in range(self.recur_depth):
            s_lm1_for_H = self.apply_dropout(s_lm1, noise_s_for_H)
            s_lm1_for_T = self.apply_dropout(s_lm1, noise_s_for_T)

together with in apply_dropout() 

       if torch.cuda.is_available(): 
              noise = noise.cuda()

could be the culprit. This means that you are doing a host to gpu copy twice for every timestep, which is costly. Instead you can take any Variable and its wrapped tensor t and create a new tensor on the same device with t.new().
 
See for example:

http://pytorch.org/docs/master/_modules/torch/nn/functional.html#alpha_dropout

**Comment by gchrupala** [comment]
Thanks for the suggestion.

But unless I'm missing something this can't be the problem, because the call to ``.cuda`` is in ``get_dropout_noise``, which is only called once in the ``forward`` method. Replacing ``.cuda`` with the ``.new`` based idiom in ``get_dropout_noise`` didn't make a noticeable difference to speed.

**Comment by samuelbroscheit** [comment]
Ok, then I am closing this issue. For me unnecessary .cuda() calls are usually the first thing that I look for. The freedom of pytorch is sometimes its curse :)
